/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/zones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Zones
         * @description Üs ve bölge merkezleri. Bölgelerin sınırı veride yok.
         */
        get: operations["get_zones_zones_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/images": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Images
         * @description Veri setindeki görüntüler: bölge, çekim saati ve varsa son değerlendirmenin seviyesi.
         */
        get: operations["list_images_images_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tracks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Tracks
         * @description Bütün track'ler, kayıtları olduğu gibi. Her track'in bittiği görüntü, o görüntünün son
         *     tamamlanmış değerlendirmesindeki temasın seviyesi ve sınıfıyla. Hiçbir görüntünün teması
         *     olmayan (görüntüsüz) track'in seviyesi ve kısa değerlendirmesi `scripts.assess_tracks`'in
         *     kaydından okunur. Hesap yapılmaz, LLM ya da tespit çağrılmaz; değerlendirmesi olmayan
         *     track'in seviyesi `None` kalır.
         */
        get: operations["list_tracks_tracks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/images/{image_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Image
         * @description Görüntünün boyutu, çekim saati, köşe koordinatları, merkezi ve bölgesi.
         */
        get: operations["get_image_images__image_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/images/{image_id}/file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Image File
         * @description Görüntü dosyası: Supabase modunda `images.file_path` ile bucket'tan, ağsız demoda
         *     yerel klasörden. Yol veri setindeki kayıttan kurulur, istekten gelen yol kullanılmaz.
         */
        get: operations["get_image_file_images__image_id__file_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/evaluations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Evaluation
         * @description Görüntüyü değerlendirir; `run`, `step` olayları ve son `brief` olayı akar.
         *
         *     Aynı görüntünün başarılı bir değerlendirmesi varsa önbellekten tekrar oynatılır
         *     (`run.cached = true`); `recompute = true` yeni değerlendirme başlatır.
         */
        post: operations["start_evaluation_evaluations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/evaluations/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Evaluation
         * @description Kayıtlı bir değerlendirmeyi bütün adımları ve brief'iyle döndürür.
         */
        get: operations["read_evaluation_evaluations__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/evaluations/{run_id}/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Chat
         * @description Değerlendirme hakkında takip sorusu; agent salt okuma araçlarıyla cevaplar.
         */
        post: operations["chat_evaluations__run_id__chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AttentionFinding
         * @description Karar LLM'inin bir dikkat maddesi ve kodun onu veriyle doğrulamasının sonucu.
         */
        AttentionFinding: {
            /** Contact */
            contact: string;
            /** Track Id */
            track_id: string | null;
            /**
             * Reason
             * @enum {string}
             */
            reason: "yaklasma" | "dolasma" | "uzun_duraklama" | "tehdit_uyarisi" | "rapor_celiskisi" | "kacirilmis_temas" | "kayit_disi" | "dikkat_gerekmiyor";
            /** Basis */
            basis: (number | string)[];
            /** Level Proposal */
            level_proposal?: ("low" | "medium" | "high" | "critical") | null;
            /** Accepted */
            accepted: boolean;
            /** Level Accepted */
            level_accepted?: boolean | null;
            /** Rejection */
            rejection?: string | null;
            /** Text */
            text?: string | null;
            /** Comment */
            comment?: string | null;
            /** Comment Rejected */
            comment_rejected?: string | null;
        };
        /** BaseInfo */
        BaseInfo: {
            /** Name */
            name: string;
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
        };
        /** Brief */
        Brief: {
            /** Image Id */
            image_id: string;
            /** Zone */
            zone: string;
            /** Capture Time */
            capture_time: string;
            /**
             * Risk Level
             * @enum {string}
             */
            risk_level: "low" | "medium" | "high" | "critical";
            /** Recommended Action */
            recommended_action: string;
            /** Is Fallback */
            is_fallback: boolean;
            /** Fallback Reason */
            fallback_reason?: string | null;
            /** Model */
            model?: string | null;
            /** Contacts */
            contacts: components["schemas"]["ContactFinding"][];
            /** Report Findings */
            report_findings?: components["schemas"]["ReportFinding"][];
            /** Text */
            text: string;
            /** Sources */
            sources: string[];
            /** Attention */
            attention?: components["schemas"]["AttentionFinding"][];
            /** Summary */
            summary?: string | null;
            /** Summary Rejected */
            summary_rejected?: string | null;
        };
        /** ChatRequest */
        ChatRequest: {
            /** Message */
            message: string;
        };
        /**
         * ContactFinding
         * @description Temas: bir Tespit ve/veya onu çekim anında karşılayan Track.
         */
        ContactFinding: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "matched" | "unregistered" | "missed";
            /** Label */
            label: string | null;
            /** Effective Label */
            effective_label: string | null;
            /** Confidence */
            confidence: number | null;
            /** Bbox */
            bbox: [
                number,
                number,
                number,
                number
            ] | null;
            location: components["schemas"]["LatLon"];
            /**
             * Is Weak
             * @default false
             */
            is_weak: boolean;
            /**
             * Is Ambiguous
             * @default false
             */
            is_ambiguous: boolean;
            /**
             * Position Estimated
             * @default false
             */
            position_estimated: boolean;
            /**
             * Type Conflict
             * @default false
             */
            type_conflict: boolean;
            /**
             * Verified Friend
             * @default false
             */
            verified_friend: boolean;
            /** Observed Labels */
            observed_labels?: components["schemas"]["LabelObservation"][];
            /** Distance To Base M */
            distance_to_base_m: number;
            /** Track Id */
            track_id?: string | null;
            /** Match Distance M */
            match_distance_m?: number | null;
            second_candidate?: components["schemas"]["TrackCandidate"] | null;
            motion?: components["schemas"]["MotionFinding"] | null;
            visual?: components["schemas"]["VisualFinding"] | null;
            /**
             * Base Level
             * @enum {string}
             */
            base_level: "low" | "medium" | "high" | "critical";
            /**
             * Final Level
             * @enum {string}
             */
            final_level: "low" | "medium" | "high" | "critical";
            /** Level Reasons */
            level_reasons?: string[];
            /** Level Basis */
            level_basis?: ("yaklasma" | "dolasma" | "uzun_duraklama" | "tehdit_uyarisi" | "rapor_celiskisi" | "kacirilmis_temas" | "kayit_disi" | "dikkat_gerekmiyor")[];
            /** Level Code */
            level_code?: string | null;
            /** Priority Score */
            priority_score?: number | null;
            /** Level Tags */
            level_tags?: string[];
            /** Level History */
            level_history?: components["schemas"]["LevelPoint"][];
            /** Adjustment Reason */
            adjustment_reason?: string | null;
            /** Adjustment Rejected */
            adjustment_rejected?: string | null;
            /**
             * Certainty
             * @enum {string}
             */
            certainty: "certain" | "likely" | "weak" | "unverified";
        };
        /** CornerCoordinates */
        CornerCoordinates: {
            /** Top Left */
            top_left: [
                number,
                number
            ];
            /** Top Right */
            top_right: [
                number,
                number
            ];
            /** Bottom Left */
            bottom_left: [
                number,
                number
            ];
            /** Bottom Right */
            bottom_right: [
                number,
                number
            ];
        };
        /**
         * EvaluationRecord
         * @description Kayıtlı bir değerlendirme: bütün adımları ve brief'i.
         */
        EvaluationRecord: {
            /** Run Id */
            run_id: string;
            /** Image Id */
            image_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "running" | "done" | "failed";
            /** Steps */
            steps: components["schemas"]["StepEvent"][];
            brief: components["schemas"]["Brief"] | null;
            /** Error */
            error: string | null;
        };
        /** EvaluationRequest */
        EvaluationRequest: {
            /** Image Id */
            image_id: string;
            /**
             * Recompute
             * @default false
             */
            recompute: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * ImageDetail
         * @description Görüntünün `image_meta.json` kaydı; karenin merkezi ve bölgesiyle.
         */
        ImageDetail: {
            /** Image Id */
            image_id: string;
            /** Width Px */
            width_px: number;
            /** Height Px */
            height_px: number;
            /** Capture Time */
            capture_time: string;
            corner_coordinates: components["schemas"]["CornerCoordinates"];
            /** Center */
            center: [
                number,
                number
            ];
            /** Zone */
            zone: string;
        };
        /** ImageSummary */
        ImageSummary: {
            /** Image Id */
            image_id: string;
            /** Zone */
            zone: string;
            /** Capture Time */
            capture_time: string;
            /** Last Risk Level */
            last_risk_level?: ("low" | "medium" | "high" | "critical") | null;
        };
        /** LabelObservation */
        LabelObservation: {
            /** Image Id */
            image_id: string;
            /** Label */
            label: string;
        };
        /** LatLon */
        LatLon: {
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
        };
        /**
         * LevelPoint
         * @description Risk motorunun bir gözlem anındaki kararı.
         */
        LevelPoint: {
            /** Time */
            time: string;
            /**
             * Level
             * @enum {string}
             */
            level: "low" | "medium" | "high" | "critical";
            /** Code */
            code: string;
            /** Score */
            score: number;
        };
        /** MotionFinding */
        MotionFinding: {
            /** Distance To Base M */
            distance_to_base_m: number;
            /** Distance To Base 30Min Ago M */
            distance_to_base_30min_ago_m: number | null;
            /** Distance To Base 60Min Ago M */
            distance_to_base_60min_ago_m: number | null;
            /**
             * Trend
             * @enum {string}
             */
            trend: "approaching" | "receding" | "stationary" | "passing" | "unknown";
            /** Route */
            route?: components["schemas"]["RoutePoint"][];
            /** Total Distance M */
            total_distance_m: number;
            /** Avg Speed Mps */
            avg_speed_mps: number;
            /** Recent Speed Mps */
            recent_speed_mps: number;
            /** Heading Deg */
            heading_deg: number | null;
            /** Stops */
            stops?: components["schemas"]["StopFinding"][];
            /** Zones Passed */
            zones_passed?: string[];
            /** Current Stop Minutes */
            current_stop_minutes: number | null;
            /** Stop Open Ended */
            stop_open_ended: boolean;
            /** Base Distance Min M */
            base_distance_min_m: number;
            /** Base Distance Max M */
            base_distance_max_m: number;
            /** Extent M */
            extent_m: number;
        };
        /**
         * ReportFinding
         * @description Rapor kararı: bir iddianın bu değerlendirmedeki sonucu (app/reports_v2).
         *
         *     Rapor risk seviyesini değiştirmez; `effect` her zaman "none"dır (ön yüzle uyum için duruyor).
         */
        ReportFinding: {
            /** Claim Id */
            claim_id: number;
            /** Report Time */
            report_time: string;
            /** Source */
            source: string;
            /** Text */
            text: string;
            /** Claim Type */
            claim_type: string;
            /** Track Id */
            track_id: string | null;
            /**
             * Verdict
             * @enum {string}
             */
            verdict: "consistent" | "contradicts" | "unverifiable" | "irrelevant";
            /**
             * Certainty
             * @enum {string}
             */
            certainty: "certain" | "likely" | "weak" | "unverified";
            /**
             * Effect
             * @enum {string}
             */
            effect: "raises" | "lowers" | "none";
            /** Reasoning */
            reasoning: string;
            /** Detail Verdict */
            detail_verdict?: string | null;
            /**
             * Dangerous Reassurance
             * @default false
             */
            dangerous_reassurance: boolean;
            /** Context Flags */
            context_flags?: string[];
            /**
             * Needs Review
             * @default false
             */
            needs_review: boolean;
            /** Rule Verdict */
            rule_verdict?: string | null;
        };
        /** RoutePoint */
        RoutePoint: {
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /** Time */
            time?: string | null;
        };
        /**
         * StepEvent
         * @description Değerlendirme adımı; arayüze SSE ile akar ve kaydedilir.
         */
        StepEvent: {
            /** Step No */
            step_no: number;
            /** Name */
            name: string;
            /** Summary */
            summary: string;
            /** Data */
            data?: {
                [key: string]: unknown;
            };
        };
        /**
         * StopFinding
         * @description Duraklama: saat (SS:DD), süre, yer ve bölge.
         */
        StopFinding: {
            /** Start */
            start: string;
            /** End */
            end: string;
            /** Minutes */
            minutes: number;
            location: components["schemas"]["LatLon"];
            /** Zone */
            zone: string;
            /** Distance To Base M */
            distance_to_base_m: number;
        };
        /** TrackCandidate */
        TrackCandidate: {
            /** Track Id */
            track_id: string;
            /** Distance M */
            distance_m: number;
        };
        /**
         * TrackOverview
         * @description Bir track'in bütün kaydı ve bittiği görüntünün son değerlendirmesindeki yeri.
         *
         *     Her track bir görüntünün çekim anında o görüntünün karesinde biter (kaydı o görüntünün
         *     son iki saatidir). Seviye ve sınıf o görüntünün son tamamlanmış değerlendirmesindeki
         *     temastan okunur; yeniden hesaplanmaz. Değerlendirme yoksa `None`.
         */
        TrackOverview: {
            /** Track Id */
            track_id: string;
            /** Start */
            start: string;
            /** End */
            end: string;
            /** Points */
            points: components["schemas"]["RoutePoint"][];
            /** Image Id */
            image_id?: string | null;
            /** Level */
            level?: ("low" | "medium" | "high" | "critical") | null;
            /** Label */
            label?: string | null;
            /** Kind */
            kind?: ("matched" | "unregistered" | "missed") | null;
            /**
             * Unframed
             * @default false
             */
            unframed: boolean;
            /** Assessment */
            assessment?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * VisualFinding
         * @description VLM'in bir tespit kutusunda gördükleri; bilemediği özellik boş kalır.
         */
        VisualFinding: {
            /** Is Vehicle */
            is_vehicle: boolean;
            /** Color */
            color: ("beyaz" | "siyah" | "gri" | "kirmizi" | "mavi" | "yesil" | "sari" | "turuncu" | "kahverengi" | "bej" | "mor") | null;
            /** Cargo */
            cargo: ("loaded" | "empty") | null;
            /** Model */
            model: string;
        };
        /** ZoneInfo */
        ZoneInfo: {
            /** Name */
            name: string;
            /** Center */
            center: [
                number,
                number
            ];
        };
        /**
         * ZonesResponse
         * @description Üs ve bölgeler, `zones.json` biçiminde. Bölgelerin sınırı yok, yalnızca merkezi var.
         */
        ZonesResponse: {
            base: components["schemas"]["BaseInfo"];
            /** Zones */
            zones: components["schemas"]["ZoneInfo"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_zones_zones_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ZonesResponse"];
                };
            };
        };
    };
    list_images_images_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageSummary"][];
                };
            };
        };
    };
    list_tracks_tracks_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrackOverview"][];
                };
            };
        };
    };
    get_image_images__image_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                image_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageDetail"];
                };
            };
            /** @description Görüntü veri setinde yok */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_image_file_images__image_id__file_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                image_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Görüntü dosyası */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/jpeg": unknown;
                    "image/png": unknown;
                };
            };
            /** @description Görüntü veri setinde yok ya da dosyası bulunamadı */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Storage'a ulaşılamadı */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    start_evaluation_evaluations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EvaluationRequest"];
            };
        };
        responses: {
            /** @description Adım olayları, son olay brief */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": unknown;
                };
            };
            /** @description Görüntü veri setinde yok */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_evaluation_evaluations__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationRecord"];
                };
            };
            /** @description Değerlendirme bulunamadı */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_evaluations__run_id__chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description `tool` olayları, son olay `answer` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": unknown;
                };
            };
            /** @description Tamamlanmış değerlendirme bulunamadı */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
